apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-predictor
  template:
    metadata:
      labels:
        app: ai-predictor
    spec:
      containers:
      - name: ai-service
        image: ai-predictor:latest
        imagePullPolicy: Never # Yeh line sabse zaroori hai
        env:
        - name: KAFKA_SERVER
          value: "kafka-service:9092"