apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-recruit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-recruit
  template:
    metadata:
      labels:
        app: smart-recruit
    spec:
      containers:
      - name: smart-recruit-app
        image: aradhana6dec/smart-recruit:latest
        imagePullPolicy: Always
        # resources section hata diya gaya hai
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: smart-recruit-service
spec:
  type: NodePort
  selector:
    app: smart-recruit
  ports:
  - port: 8080
    targetPort: 8080